Python programmers will often suggest that there many ways the language can be used to solve a particular problem. But that some are more appropriate than others. The best solutions are celebrated as Idiomatic Python.  
A sort of sub-language within Python, Pandas has its own set of idioms. We've alluded to some of these already, such as using vectorization whenever possible, and not using iterative loops if you don't need to. Several developers and users within the Panda's community have used the term __pandorable__ for these idioms.

In [1]:
import pandas as pd
import numpy as np
import timeit

In [2]:
df = pd.read_csv('census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [4]:
#pandorable
(df.where(df['SUMLEV']==50)
   .dropna()
   .set_index(['STNAME','CTYNAME'])
   .rename(columns={'ESTIMATESBASE2010':'Estimates Base 2010'}))

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County       50.0     3.0       6.0    1.0     1.0
        Baldwin County       50.0     3.0       6.0    1.0     3.0
        Barbour County       50.0     3.0       6.0    1.0     5.0
        Bibb County          50.0     3.0       6.0    1.0     7.0
        Blount County        50.0     3.0       6.0    1.0     9.0
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County    50.0     4.0       8.0   56.0    37.0
        Teton County         50.0     4.0       8.0   56.0    39.0
        Uinta County         50.0     4.0       8.0   56.0    41.0
        Washakie County      50.0     4.0       8.0   56.0    43.0
        Weston County        50.0     4.0       8.0   56.0    45.0

                           CENSUS2010POP  Estimates Base 2010  \
STNAME  CTYNAME
Alabama Autauga County           54571.0              54571.0
        Baldwin County          182265.0             182265.0
        Barbour County           27457.0              27457.0
        Bibb County              22915.0              22919.0
        Blount County            57322.0              57322.0
...                                  ...                  ...
Wyoming Sweetwater County        43806.0              43806.0
        Teton County             21294.0              21294.0
        Uinta County             21118.0              21118.0
        Washakie County           8533.0               8533.0
        Weston County             7208.0               7208.0

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME
Alabama Autauga County             54660.0          55253.0          55175.0
        Baldwin County            183193.0         186659.0         190396.0
        Barbour County             27341.0          27226.0          27159.0
        Bibb County                22861.0          22733.0          22642.0
        Blount County              57373.0          57711.0          57776.0
...                                    ...              ...              ...
Wyoming Sweetwater County          43593.0          44041.0          45104.0
        Teton County               21297.0          21482.0          21697.0
        Uinta County               21102.0          20912.0          20989.0
        Washakie County             8545.0           8469.0           8443.0
        Weston County               7181.0           7114.0           7065.0

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME            ...
Alabama Autauga County     ...          7.242091         -2.915927
        Baldwin County     ...         14.832960         17.647293
        Barbour County     ...         -4.728132         -2.500690
        Bibb County        ...         -5.527043         -5.068871
        Blount County      ...          1.807375         -1.177622
...                        ...               ...               ...
Wyoming Sweetwater County  ...          1.072643         16.243199
        Teton County       ...         -1.589565          0.972695
        Uinta County       ...        -17.755986         -4.916350
        Washakie County    ...        -11.637475         -0.827815
        Weston County      ...        -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In [5]:
#non-pandorable
df = df[df['SUMLEV']==50]
df.set_index(['STNAME','CTYNAME'], inplace=True)
df.rename(columns={'ESTIMATESBASE2010':'Estimates Base 2010'})

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County         50       3         6      1       1
        Baldwin County         50       3         6      1       3
        Barbour County         50       3         6      1       5
        Bibb County            50       3         6      1       7
        Blount County          50       3         6      1       9
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County      50       4         8     56      37
        Teton County           50       4         8     56      39
        Uinta County           50       4         8     56      41
        Washakie County        50       4         8     56      43
        Weston County          50       4         8     56      45

                           CENSUS2010POP  Estimates Base 2010  \
STNAME  CTYNAME
Alabama Autauga County             54571                54571
        Baldwin County            182265               182265
        Barbour County             27457                27457
        Bibb County                22915                22919
        Blount County              57322                57322
...                                  ...                  ...
Wyoming Sweetwater County          43806                43806
        Teton County               21294                21294
        Uinta County               21118                21118
        Washakie County             8533                 8533
        Weston County               7208                 7208

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME
Alabama Autauga County               54660            55253            55175
        Baldwin County              183193           186659           190396
        Barbour County               27341            27226            27159
        Bibb County                  22861            22733            22642
        Blount County                57373            57711            57776
...                                    ...              ...              ...
Wyoming Sweetwater County            43593            44041            45104
        Teton County                 21297            21482            21697
        Uinta County                 21102            20912            20989
        Washakie County               8545             8469             8443
        Weston County                 7181             7114             7065

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME            ...
Alabama Autauga County     ...          7.242091         -2.915927
        Baldwin County     ...         14.832960         17.647293
        Barbour County     ...         -4.728132         -2.500690
        Bibb County        ...         -5.527043         -5.068871
        Blount County      ...          1.807375         -1.177622
...                        ...               ...               ...
Wyoming Sweetwater County  ...          1.072643         16.243199
        Teton County       ...         -1.589565          0.972695
        Uinta County       ...        -17.755986         -4.916350
        Washakie County    ...        -11.637475         -0.827815
        Weston County      ...        -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

TIMEIT pandorable vs non-pandorable :-

In [9]:
#pandoarable
def first_approach():
    global df
    return (df.where(df['SUMLEV']==50)
            .dropna()
            .set_index(['STNAME','CTYNAME'])
            .rename(columns={'ESTIMATESBASE2010':'Estimates Base 2010'}))

df = pd.read_csv('census.csv')
timeit.timeit(first_approach, number=10) # number=10 no. of times

0.5580749000000651

In [10]:
#non-pandorable
def second_approach():
    global df
    new_df = df[df['SUMLEV']==50]
    new_df.set_index(['STNAME','CTYNAME'],inplace=True)
    return new_df.rename(columns={'ESTIMATESBASE2010':'Estimates Base 2010'})

df = pd.read_csv('census.csv')
timeit.timeit(second_approach, number=10) # number=10 no. of times

0.09214930000234745

**Conclusion** - What appears to be stylistic idioms might have performance issues that you need to consider as well.

Lets find min and max along columns of population estimate from 2011 to 2015 -

In [16]:
df[['POPESTIMATE2011',
    'POPESTIMATE2012',
    'POPESTIMATE2013',
    'POPESTIMATE2014',
    'POPESTIMATE2015']]

,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
0,4801108,4816089,4830533,4846411,4858979
1,55253,55175,55038,55290,55347
2,186659,190396,195126,199713,203709
3,27226,27159,26973,26815,26489
4,22733,22642,22512,22549,22583
...,...,...,...,...,...
3188,44041,45104,45162,44925,44626
3189,21482,21697,22347,22905,23125
3190,20912,20989,21022,20903,20822
3191,8469,8443,8443,8316,8328
3192,7114,7065,7160,7185,7234

In [13]:
def min_max(row):
    data = row[['POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({'min':np.min(data),'max':np.max(data)})

df.apply(min_max,axis=1)

          min      max
0     4801108  4858979
1       55038    55347
2      186659   203709
3       26489    27226
4       22512    22733
...       ...      ...
3188    44041    45162
3189    21482    23125
3190    20822    21022
3191     8316     8469
3192     7065     7234

[3193 rows x 2 columns]

Another way adding min max columns to dataframe itself -

In [20]:
def min_max(row):
    data = row[['POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    return row

df.apply(min_max, axis=1).head()[['POPESTIMATE2011',
                                  'POPESTIMATE2012',
                                  'POPESTIMATE2013',
                                  'POPESTIMATE2014',
                                  'POPESTIMATE2015', 'max', 'min']]

,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,max,min
0,4801108,4816089,4830533,4846411,4858979,4858979,4801108
1,55253,55175,55038,55290,55347,55347,55038
2,186659,190396,195126,199713,203709,203709,186659
3,27226,27159,26973,26815,26489,27226,26489
4,22733,22642,22512,22549,22583,22733,22512

Using Lambda -

In [23]:
rows = ['POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']
df.apply(lambda x:pd.Series({'max':np.max(x[rows]),'min':np.min(x[rows])}), axis=1)

          max      min
0     4858979  4801108
1       55347    55038
2      203709   186659
3       27226    26489
4       22733    22512
...       ...      ...
3188    45162    44041
3189    23125    21482
3190    21022    20822
3191     8469     8316
3192     7234     7065

[3193 rows x 2 columns]